### ISSUE TITLE
Is it works, if....

### ISSUE THREAD

**Issue by ghost** [PascalNoisette/logstash-input-gunzip#1]
Hi, @PascalNoisette
I don't know how this plugin actually works, and I just want to know ... I have a case where I have to read a lot of gzip logs to be sent to Elasticsearch. And these logs (gzip file) have different names, based on the timestamp.

the question is, can I use this plugin to process all the data?

for details file and directory hierarchy that I have as below:

```
* The directory and files name is generated based on date timestamp.

└── all-logs
    ├──  2019-12-24
    │     ├── 12.44.01-12.49.01.gz
    │     ├── 12.49.01-12.54.01.gz
    │     ├── 12.54.01-12.59.01.gz
    │     ├── 12.59.01-13.04.01.gz
    │     ├── 13.04.01-13.09.01.gz
    │     ├── [..etc..]
    ├── 2019-12-26
    │     ├── 08.43.46-08.48.46.gz
    │     ├── 08.44.01-08.49.01.gz
    │     ├── 08.49.01-08.54.01.gz
    │     ├── 08.54.01-08.59.01.gz
    │     ├── 08.59.01-09.04.01.gz
    │     ├── [..etc..]
    ├── 2019-12-27
    │     ├── 00.04.01-00.09.01.gz
    │     ├── 00.09.01-00.14.01.gz
    │     ├── 00.14.01-00.19.01.gz
    │     ├── 00.19.01-00.24.01.gz
    │     ├── [..etc..]
    ├── 2019-12-27
    │     ├── [..etc..]
```
Please reply to my question ... I need help for advance

**Comment by PascalNoisette** [comment]
Hi !

I think you should use instead [plugins-inputs-file](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-mode) in `mode=read` henceforth because my plugin is now deprecated and it was done back when gzip was not supported.

Regards,
Pascal Noisette
